default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "postgres" } %>
  port: <%= ENV.fetch("DB_PORT") { "5432" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: code_challenge_development

test:
  <<: *default
  database: code_challenge_test

production:
  <<: *default
  database: code_challenge_production
  username: code_challenge
  password: <%= ENV['CODE_CHALLENGE_DATABASE_PASSWORD'] %>
